# Generated by Django 5.2.15 on 2026-07-03 08:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên cụm sân')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('district', models.CharField(max_length=50, verbose_name='Quận/Huyện')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Vĩ độ (Latitude)')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kinh độ (Longitude)')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả sân')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to=settings.AUTH_USER_MODEL, verbose_name='Chủ sân')),
            ],
            options={
                'verbose_name': 'Sân cầu lông',
                'verbose_name_plural': 'Danh sách Sân cầu lông',
            },
        ),
        migrations.CreateModel(
            name='CourtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='court_images/', verbose_name='Ảnh sân')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='courts.court', verbose_name='Sân cầu lông')),
            ],
            options={
                'verbose_name': 'Hình ảnh sân',
                'verbose_name_plural': 'Hình ảnh sân',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá (sao)')),
                ('comment', models.TextField(blank=True, verbose_name='Nhận xét')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đánh giá')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courts.court', verbose_name='Sân cầu lông')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người chơi')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Danh sách Đánh giá',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá thuê (VND/giờ)')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='courts.court', verbose_name='Sân cầu lông')),
            ],
            options={
                'verbose_name': 'Khung giờ mẫu',
                'verbose_name_plural': 'Khung giờ mẫu',
                'ordering': ['start_time'],
            },
        ),
    ]
