# Generated by Django 5.2.15 on 2026-07-03 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày đặt chơi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt cọc'), ('CONFIRMED', 'Đã cọc (Thành công)'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=15, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo đặt sân')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='courts.court', verbose_name='Sân cầu lông')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Người chơi')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='courts.timeslot', verbose_name='Khung giờ đặt')),
            ],
            options={
                'verbose_name': 'Đặt sân',
                'verbose_name_plural': 'Danh sách Đặt sân',
                'ordering': ['-date', 'time_slot__start_time'],
                'constraints': [models.UniqueConstraint(fields=('court', 'date', 'time_slot'), name='unique_court_booking_slot')],
            },
        ),
    ]
